### ISSUE TITLE
0.2 tracking issue

### ISSUE THREAD

**Issue by xlz** [OpenKinect/libfreenect2#558]
Major changes and remaining issues:

##### Performance optimization features

- [x] CUDA depth decoder
- [x] VA-API JPEG decoder
- [x] VideoToolbox JPEG decoder (Francisco Facioni)
- [x] Tegra JPEG decoder
- [x] Zerocopy between packet processors and frame listeners

##### New features

- [x] OpenNI2 integration (Zou Hanya)
- [x] Depth only registration functions (Matthieu FT)
- [x] Raw data dumping interfaces  (Brendan Burns)

##### Improvement and bug fixes

- [x] CPU depth processor cleanup (Albert Hofkamp)
- [x] Interface to disable RGB or depth stream
- [x] Improved USB error checking
- [x] Documentation for Jetson TK1
- [x] Complete frame->format etc.
- [x] Bail out when processors fail
- [x] Multi-Kinects testing

##### API changes from 0.1 to 0.2

- (New) `Freenect2Device::startStreams()` to selectively start rgb or depth stream.
- (New) `DumpPacketPipeline`
- (New) `CudaPacketPipeline`
- (New) `Registration::undistortDepth()` `Registration::getPointXYZ()`
- (Semantics change) If `Freenect2Device::start()` or `Freenect2Device::stop()` returns false, the usb device is in an undefined state and it must be closed.
- (Semantics change, Mac only) The default color processor becomes VT from TurboJPEG.
- (Semantics change, Intel & Linux only) The default color processor becomes VAAPI from TurboJPEG. If VAAPI fails, it falls back to TurboJPEG. Environment variable `LIBVA_DRIVER_NAME=none` can disable it and make it fall back.

##### Pushed back to 0.3 (for a rapid 0.2 release)
- WIP: Raw data replay interfaces/tools (Brendan Burns)
- Firmware upgrade tool
- Gray output of JPEG decoders
- SWIG bindings
- Python binding (pyfreenect2) (Nathan Ringo)
- Do something about the 10th layer.

Probably not possible for 0.2:

- Zerocopy libusb transfer

**Comment by xlz** [comment]
@floe People are having weird issues with beignet 1.0.3 https://github.com/code-iai/iai_kinect2/issues/236, where Protonect works fine but beignet produces some mysterious errors within iai_kinect2.

Is it possible to provide beignet 1.1.1 in your ppa? 

For the record, I built a ported beignet 1.1.1 to Ubuntu 14.04 with the beignet sources (1.1.1) from Ubuntu 16.04, changed `debian/control` to remove build dependencies on `clang, llvm`, installed `clang-3.6 libclang-3.6-dev`, and `apt-src build beignet-dev` built some beignet 1.1.1 debs.

**Comment by floe** [comment]
Sorry for the silence, been sick for a while. I'll see what I can put together, doesn't sound like a big problem for the PPA.

**Comment by floe** [comment]
I've created a new PPA: https://launchpad.net/~floe/+archive/ubuntu/beignet
Beignet 1.1.1 is available for trusty:amd64, doesn't seem to build for i386...?

**Comment by floe** [comment]
Update: took some fiddling, now also available for i386.

**Comment by floe** [comment]
I guess it's not worth to support other non-LTS releases via the PPAs, as 16.04 will be out soon anyway?

**Comment by sunnysunnyran** [comment]
somebody who know how to matting from multi kinect?thankyou very much

**Comment by floe** [comment]
@sunnysunnyran please open a new issue with a specific question and don't just dump your comments into arbitrary threads.

**Comment by xlz** [comment]
rc2

**Comment by xlz** [comment]
For anyone interested, what is left is just updating the docs and testing. The code is pretty much finished. 

Nvidia's kayccc is following up with the problem on Jetson TX1, but I don't think he will have an answer any time soon.

I'm busy these two weeks. Hopefully I can make a release by the end of this month.

**Comment by xlz** [comment]
I published 0.2 release.

**Comment by floe** [comment]
Great work! I'll check with Zenodo if anything needs to be done regarding the DOI.
